import * as assert from 'assert';

import { isAttribution, stripAttribution } from '../attribution';

const FENCE = '```';
const GENERATED = '🤖 Generated with [Claude Code](https://claude.com/claude-code)';

suite('attribution', () => {
	test('recognizes the trailers and credits models add themselves', () => {
		assert.ok(isAttribution('Co-Authored-By: Claude <noreply@anthropic.com>'));
		assert.ok(isAttribution('Co-authored-by: Claude Opus 5 (1M context) <noreply@anthropic.com>'));
		assert.ok(isAttribution('Signed-off-by: Someone <someone@example.com>'));
		assert.ok(isAttribution(GENERATED));
		assert.ok(isAttribution('Generated by Gemini'));
		assert.ok(isAttribution('Created with Claude Code'));
	});

	test('leaves ordinary body text alone', () => {
		assert.ok(!isAttribution('- Add Co-authored-by support to the signature editor'));
		assert.ok(!isAttribution('- Generated with esbuild, so the bundle stays small'));
		assert.ok(!isAttribution('Refs: ABC-123'));
		assert.ok(!isAttribution('fix(signature): drop a trailer whose variables resolve to nothing'));
	});

	test('drops a footer and the blank line it left behind', () => {
		const raw = [
			'feat(pr): pick the base branch per repository',
			'',
			'- Remember the last base keyed by repository',
			'',
			'Co-Authored-By: Claude <noreply@anthropic.com>',
			GENERATED,
		].join('\n');

		assert.strictEqual(stripAttribution(raw), [
			'feat(pr): pick the base branch per repository',
			'',
			'- Remember the last base keyed by repository',
		].join('\n'));
	});

	test('keeps a configured-looking trailer that is not attribution', () => {
		const raw = ['fix(cli): widen the PATH probe', '', 'Refs: ABC-123'].join('\n');

		assert.strictEqual(stripAttribution(raw), raw);
	});

	test('keeps attribution inside a fenced block', () => {
		const raw = [
			'Document the signature setting',
			'',
			'## Changes',
			'- Show a worked example:',
			'',
			FENCE,
			'fix(x): do a thing',
			'',
			'Co-authored-by: Your Name <you@example.com>',
			FENCE,
		].join('\n');

		assert.strictEqual(stripAttribution(raw), raw);
	});

	test('drops a credit that follows a closed fence', () => {
		const raw = [
			FENCE,
			'fix(x): do a thing',
			FENCE,
			'',
			GENERATED,
		].join('\n');

		assert.strictEqual(stripAttribution(raw), [FENCE, 'fix(x): do a thing', FENCE].join('\n'));
	});
});
